# Clippy configuration
# Allow some lints that are too restrictive
allow-unwrap-in-tests = true
allow-expect-in-tests = true

# Deny certain lints that are particularly important
deny = [
  "clippy::unwrap_used",
  "clippy::expect_used",
  "clippy::unimplemented",
  "clippy::todo",
  "clippy::panic",
  "clippy::indexing_slicing",
  "clippy::unwrap_in_result",
  "clippy::unwrap_used",
  "clippy::expect_used",
  "clippy::missing_docs_in_private_items",
  "clippy::implicit_return",
  "clippy::shadow_unrelated",
  "clippy::shadow_same",
  "clippy::string_add",
  "clippy::wildcard_imports",
  "clippy::redundant_closure_for_method_calls",
  "clippy::use_self",
  "clippy::mut_mut",
  "clippy::needless_pass_by_value",
  "clippy::option_option",
  "clippy::result_map_unwrap_or_else",
]

# Warn on other lints
warn = [
  "clippy::all",
  "clippy::pedantic",
  "clippy::nursery",
  "clippy::cargo",
  "clippy::complexity",
  "clippy::correctness",
  "clippy::perf",
  "clippy::style",
  "clippy::suspicious",
  "clippy::doc_markdown",
  "clippy::missing_errors_doc",
  "clippy::missing_panics_doc",
  "clippy::must_use_candidate",
  "clippy::clone_on_ref_ptr",
  "clippy::cognitive_complexity",
  "clippy::derive_partial_eq_without_eq",
  "clippy::empty_enum",
  "clippy::enum_glob_use",
  "clippy::equatable_if_let",
  "clippy::fallible_impl_from",
  "clippy::if_not_else",
  "clippy::inefficient_to_string",
  "clippy::large_stack_arrays",
  "clippy::manual_ok_or",
  "clippy::match_same_arms",
  "clippy::needless_continue",
  "clippy::needless_for_each",
]

# Configure specific lints
cognitive-complexity-threshold = 15
type-complexity-threshold = 250
too-many-arguments-threshold = 5
too-many-lines-threshold = 100
